Disable default Vagrant shared directory
By default, Vagrant will share your project directory (the directory
with the `Vagrantfile`) to `/vagrant`. [1]

This is problematic when using boxes without guest additions installed
as the share type falls back to rsync. There are some problems with
symlinks when using rsync:

    ==> default: Rsyncing folder: /private/tmp/alaveteli/ => /vagrant
    There was an error when attempting to rsync a synced folder.
    Please inspect the error message below for more info.

    Host path: /private/tmp/alaveteli/
    Guest path: /vagrant
    Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/var/folders/60/f99tgc9j20qfh9sgfnh3nf_80000gn/T/ssh.813 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/private/tmp/alaveteli/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/private/tmp/alaveteli/" "vagrant@127.0.0.1:/vagrant"
    Error: symlink has no referent: "/private/tmp/alaveteli/public/views_cache"
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1249) [sender=3.1.2]

I think the gist of what's happening here is:

* You create the VM.
* Vagrant goes "oh, there are not guest additions, so I'll share the
  project directory via rsync".
* The vbguest-plugin installs the guest additions (if you have it
  installed – you should ;)).
* By then though, its too late. Vagrant has already shared the project
  directory with rsync, causing the error above.

This commit disables the default share because we install Alaveteli to
`/home/vagrant/alaveteli` through the install script. We don't use the
default share, so hopefully this will also have a performance benefit.

If we later decide we want the default project directory and the rsync
problem still exists, we can force the share type to `virtualbox` [2]
which also fixed the problem:

    - config.vm.synced_folder '.', '/vagrant', disabled: true
    + config.vm.synced_folder '.', '/vagrant', type: 'virtualbox'

[1] https://www.vagrantup.com/docs/synced-folders/
[2] https://github.com/devsecops/bootcamp/issues/84