Check whether pro features are already enabled during signup
An error is raised if the pro signup code attempts to enable a feature
which has already been enabled. e.g. if a user had a previous
subscription (or has had the poller enabled manually for some reason)

Example error:
ERROR: duplicate key value violates unique constraint "index_flipper_gates_on_feature_key_and_key_and_value" DETAIL: Key (feature_key, key, value)=(accept_mail_from_poller, actors, User;8) already exists.

Handled here as in removing the pro role, this PR allows the same user
to be eligible for pro signup for a second time.